//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SC20260_AWS_Test_01
{
    
    internal partial class ResourcesSecret
    {
        private static System.Resources.ResourceManager manager;
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((ResourcesSecret.manager == null))
                {
                    ResourcesSecret.manager = new System.Resources.ResourceManager("SC20260_AWS_Test_01.ResourcesSecret", typeof(ResourcesSecret).Assembly);
                }
                return ResourcesSecret.manager;
            }
        }
        internal static string GetString(ResourcesSecret.StringResources id)
        {
            return ((string)(ResourceManager.GetObject(((short)(id)))));
        }
        internal static byte[] GetBytes(ResourcesSecret.BinaryResources id)
        {
            return ((byte[])(ResourceManager.GetObject(((short)(id)))));
        }
        [System.SerializableAttribute()]
        internal enum StringResources : short
        {
            WifiSSID_1 = -25251,
            WifiKey_1 = -14127,
            iotArnString = -1143,
            c9examplebc_private_pem = 27507,
        }
        [System.SerializableAttribute()]
        internal enum BinaryResources : short
        {
            c9examplebc_certificate_pem = 9264,
        }
    }
}
